export default {
	// TYPE ACTIONS BUTTONS
	CELL_CHANGE_LIST:             'cell_change_list',
	CELL_ACTION_BUTTON_NEW:       'new',
	CELL_ACTION_BUTTON_CANCEL:    'cancel',
	CELL_ACTION_BUTTON_CONFIRM:   'confirm',

	// TYPE EVENT ACTIONS
	ACTION_FIND_CELL:   'CELL_FIND',
	ACTION_RELOAD_CELL: 'CELL_RELOAD',
	ACTION_CREATE_CELL: 'CELL_CREATE',
	ACTION_UPDATE_CELL: 'CELL_UPDATE',
	ACTION_DELETE_CELL: 'CELL_DELETE'
};
