export default {
	// TYPE ACTIONS BUTTONS
	CONGR_CHANGE_LIST:             'org_change_list',
	CONGR_ACTION_BUTTON_NEW:       'new',
	CONGR_ACTION_BUTTON_CANCEL:    'cancel',
	CONGR_ACTION_BUTTON_CONFIRM:   'confirm',

	// TYPE EVENT ACTIONS
	ACTION_FIND_CONGR:   'CONGR_FIND',
	ACTION_RELOAD_CONGR: 'CONGR_RELOAD',
	ACTION_CREATE_CONGR: 'CONGR_CREATE',
	ACTION_UPDATE_CONGR: 'CONGR_UPDATE',
	ACTION_DELETE_CONGR: 'CONGR_DELETE'
};
