export default {
	// TYPE ACTIONS BUTTONS
	GRID_CHANGE_LIST:             'grid_change_list',
	GRID_ACTION_BUTTON_NEW:       'new',
	GRID_ACTION_BUTTON_CANCEL:    'cancel',
	GRID_ACTION_BUTTON_CONFIRM:   'confirm',

	// TYPE EVENT ACTIONS
	ACTION_FIND_GRID:   'GRID_FIND',
	ACTION_RELOAD_GRID: 'GRID_RELOAD',
	ACTION_CREATE_GRID: 'GRID_CREATE',
	ACTION_UPDATE_GRID: 'GRID_UPDATE',
	ACTION_DELETE_GRID: 'GRID_DELETE'
};
