export default {
	// TYPE ACTIONS BUTTONS
	ORG_ACTION_BUTTON_NEW: 'new',
	ORG_ACTION_BUTTON_CANCEL: 'cancel',
	ORG_ACTION_BUTTON_CONFIRM: 'confirm',

	// TYPE EVENT ACTIONS
	ACTION_FIND_ORG:   'ORG_FIND',
	ACTION_RELOAD_ORG:   'ORG_RELOAD',
	ACTION_CREATE_ORG: 'ORG_CREATE',
	ACTION_UPDATE_ORG: 'ORG_UPDATE',
	ACTION_DELETE_ORG: 'ORG_DELETE'
};
