export default {
	// TYPE ACTIONS BUTTONS
	USER_CHANGE_LIST: 'user_change_list',
	USER_ACTION_BUTTON_NEW: 'new',
	USER_ACTION_BUTTON_CANCEL: 'cancel',
	USER_ACTION_BUTTON_CONFIRM: 'confirm',

	// TYPE EVENT ACTIONS
	ACTION_FIND_USER:   'USER_FIND',
	ACTION_RELOAD_USER: 'USER_RELOAD',
	ACTION_CREATE_USER: 'USER_CREATE',
	ACTION_UPDATE_USER: 'USER_UPDATE',
	ACTION_DELETE_USER: 'USER_DELETE'
};
